services:
  db:
    image: postgres:17-alpine
    container_name: fms-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-fms_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: denoland/deno:2.7.14
    container_name: fms-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: task dev
    environment:
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-fms_db}
      JWT_SECRET: ${JWT_SECRET:-supersecret}
      DENO_ENV: development
    depends_on:
      - db

volumes:
  postgres_data:
